FORMAT: 1A
HOST: http://youknownothing.fyi/api/

# SWEGoT

SWEGoT is a simple API allowing avid fans of the Game of Thrones to view data about their favorite book and TV series!

## Episodes Collection [/episodes]

### List All Episodes [GET]

+ Response 200 (application/json)

        {
            "episodes": [
                {
                    "name": "The Kingsroad", 
                    "predecessor": "Winter Is Coming", 
                    "season": 1, 
                    "successor": "Lord Snow"
                }, 
                {
                    "name": "Lord Snow", 
                    "predecessor": "The Kingsroad", 
                    "season": 1, 
                    "successor": "Cripples, Bastards, and Broken Things"
                }, 
                {
                    "name": "Winter Is Coming", 
                    "predecessor": null, 
                    "season": 1, 
                    "successor": "The Kingsroad"
                },
                {
                    ...
                }
            ]
        }
        
## Specific Episode [/episodes/{name}]

### Get information about a specific episode [GET]
+ Parameters
    + name (String) - name of the specific episode

+ Response 200 (application/json)

        {
            "episode": {
                "name": "Winter Is Coming", 
                "predecessor": null, 
                "season": 1, 
                "successor": "The Kingsroad"
            }
        }
        
## Houses Collection [/houses]

### List All Houses [GET]

+ Response 200 (application/json)

        {
            "houses": [
                    {
                        "current_lord": null, 
                        "name": "Henly (House Ashford)", 
                        "overlord": null, 
                        "region": null, 
                        "title": null
                    }, 
                    {
                        "current_lord": null, 
                        "name": "Norren (House Mooton)", 
                        "overlord": null, 
                        "region": null, 
                        "title": "Maester"
                    }, 
                    {
                        "current_lord": null, 
                        "name": "House of the Undying servitor", 
                        "overlord": null, 
                        "region": null, 
                        "title": null
                    }, 
                    {
                        ...
                    }
            ]
        }

## Specific House [/houses/{name}]

### Get information about a specific house [GET]
+ Parameters
    + name (String) - name of the specific house 

+ Response 200 (application/json)

        {
            "house": {
                "current_lord": null, 
                "name": "House Stark", 
                "overlord": "House Baratheon of King's Landing", 
                "region": "North", 
                "title": "King in the North"
            }
        }
        
## Characters Collection [/characters]

### List All Houses [GET]

+ Response 200 (application/json)

        {
            "characters": [
                {
                    "actor": null, 
                    "father": null, 
                    "house": "House Hightower", 
                    "mother": null, 
                    "name": "Abelar Hightower", 
                    "spouse": null, 
                    "titles": "Ser"
                }, 
                {
                    "actor": null, 
                    "father": null, 
                    "house": "House Frey", 
                    "mother": null, 
                    "name": "Addam Frey", 
                    "spouse": null, 
                    "titles": "Ser"
                }, 
                {
                    "actor": null, 
                    "father": null, 
                    "house": null, 
                    "mother": null, 
                    "name": "Addam", 
                    "spouse": null, 
                    "titles": "Ser"
                },
                {
                    ...
                }
        ]
    }

## Specific Character [/characters/{id}]

### Get information about a specific character [GET]
+ Parameters
    + name (String) - name of the specific character

+ Response 200 (application/json)

        {
            "character": {
                "actor": null, 
                "father": null, 
                "house": "House Stark", 
                "mother": null, 
                "name": "Jon Snow", 
                "spouse": null, 
                "titles": "Lord Commander of the Night&apos;s Watch"
            }
        }
}